---
title: "3. házi feladat (HF3)"
output: html_document
---

Beadási határidő: október 25. éjfél

Beküldés: a Microsoft Teams felületén keresztül

Adj szöveges választ is, ahol a feladatkitűzés ezt kéri!

---

## 1. feladat (HF3/1) (10 pont)

Ebben a feladatban a 2016-os riói olimpián részt vett sportolók adatait fogjuk elemezni.

**a)** (1 pont)

- Töltsd be a sportolók adatait tartlmazó [csv fájlt](https://raw.githubusercontent.com/flother/rio2016/master/athletes.csv) egy R data frame-be (közvetlenül az internetről, a fájl saját gépre való letöltése nélkül).

- Írj egy olyan függvényt, mely nemzetenként (a bemenő paraméter az országkód) meghatározza az adott ország (2016-ban) többszörösen érmes sportolóit!

- Írd ki a többszörösen érmes magyar sportolók neveit megszerzett érmeik típusával és számával együtt!

**b)** (1 pont)

A órán bemutatott Notebook02-ben írtunk egy Python függvényt, mely a születési időből meghatározta a kort.

- Hasonló logika alapján írj egy ilyen R függvényt!
<p>><font size=2>Tipp: használd az *as.POSIXlt* függvényt!</font></p>

- Az előbb definiált függvény segítségével adj hozzá a data frame-hez egy új oszlopot, amiben megadod, hogy a sportoló hány éves volt az olimpia nyitónapján.

**c)** (2 pont)

Hisztogramok készítése

- Ábrázold a női és férfi sportolók magasságának eloszlását külön-külön hisztogramon, de a hisztogramokat helyezd ugyanarra az ábrára különböző színekkel! Figyelj a színezésnél a hisztogramok átfedő részeire is! <p>><font size=2>Tipp: a ggplot függvényben használd az aes(x = height, fill = sex) opciót!</font></p>

- Készíts egy új ábrát, de most a *+ geom_histogram()* függvényben használd az *aes(y = ..density..)* opciót! Az ábrához adj hozzá egy-egy az adatokra illesztett normális sűrűségfüggvényt nemenként külön-külön!
<p>><font size=2>Tipp: használd a *+ stat_function(fun = dnorm)* függvényt a megfelelő paraméterekkel!</font></p>

**d)** (1 pont)

Tekintsük az alábbi három sportág férfi sportolóit: kosárlabda, gimnasztika, birkózás.

- Ábrázold pontdiagramon ezeket a sportolókat, úgy hogy az x-tengelyen a sportoló magassága, az y-tengelyen pedig a sportoló súlya jelenjen meg. A pontok színe a három sportág szerint legyen különböző.

**e)** (1 pont)

Ki tudjuk találni a sportágat?

- Az előző feladatban részletezett három sportág férfi sportolóinak sportágát szeretnénk megjósolni a magasság, súly és kor attribútumok alapján. Taníts naiv Bayes osztályozót a három sportág férfi sportolóit tartalmazó adatokok véletlenszerűen választott 2/3-án, és teszteld a maradék 1/3-on.
<p>><font size=2>Tipp: használd az *e1071* csomag *naiveBayes* függvényét!</font></p>

- Írd ki a tévesztési mátrixot (3x3-as mátrix lesz)!
<p>><font size=2>Tipp: használd a *table* függvényt!</font></p>

- Milyen arányban találta el a helyes címkét az algoritmus a tesztadatokon?

**f)** (2 pont)

Ismételd meg az előző feladat osztályozási feladatát, de most előbb diszkretizáld a három attribútumot!

- Mindhárom esetben hozz létre low, medium és high csoportokat az alsó és felső tercilisnek megfelelően. <p>><font size=2>Tipp: használd a *qunatile* függvényt!</font></p>

- Az e) vagy f) esetben teljesít jobban az osztályozó? 

- Írd ki az a priori osztályvalószínűségeket, és az attribútumok feltételes valószínűségeit az osztályváltozó értékét feltéve! (Ezeket az értékeket nem kell külön kiszámolni, egyszerűen lehívhatók a modellből.)

**g)** (1 pont)

Az előzőekben használt sportolói adattábla alapján készíts egy olyan adattáblát, ami azt tartalmazza, hogy az adott sportból hány női, illetve hány férfi versenyző érkezett az olimpiára!

- Képezz új oszlopot: számold ki minden sporthoz a nők arányát.

- Írd ki a nők részvételi aránya alaján az első és az utolsó 5 sportágat. 

**h)** (1 pont)

Töltsd be az Adatok mappában található countries_rio.csv fájlt!

- Az előzőekben használt sportolói adattábla alapján egészítsd ki az országok adattábláját egy új oszloppal, ami az adott ország összes megszerzett érmét tartalmazza! Figyelj arra, hogy az országok adattáblájában kevesebb ország szerepel, mint ahány országkód van a sportolói adattáblában (pl. a ROT - Refugee Olympic Team vagy az IOA - Independent Olympians nem szerpel), ezeket hagyd figyelmen kívül!
<p>><font size=2>Tipp: használd a *plyr* csomagból a *ddply* függvényt, majd használd a *merge* függvényt!</font></p>

- Képezz új oszlot az országok adattáblájában! Számold ki az adott országból érkező sportolók egy főre jutó számát (az ország népességéhez viszonyítva). Melyik országoknak a legnagyobb e mutatója? Írd ki a toplista első 10 helyezettjét!

- Ábrázold az érmek számát az egy főre jutó GDP függvényében pontfelhőként!

---

## 2. feladat (HF3/2) (5 pont)

Ebben a feladatban billentyűlenyomások nyers adataiból fogunk létrehozni idősoros adatokat, majd az idősorok között DTW távolságot számolunk.

**a)** (4 pont)

Idősorok létrehozása

- Töltsd be az Adatok mappában található raw_data.txt fájlt R-be. Ebben a fájlban néhány felhasználótól ugyanazon rövid szöveg többszöri begépeléséből származó billentyűlenyomási adatokat találod.

- Hozz létre kétfajta idősort (numerikus vektort) a nyers adatokból gépelésenkét!
<p>><font size=2>Tipp: hasznos függvények a beolvasához, majd a sorok szétvágáshoz: *readLines* és *strsplit*.</font></p>
    + Az első idősor tartalmazza a billentyűlenyomások időtartamát. Egy lenyomás időtartama alatt most az egymásnak megfelelő *keydown* és *keyup* események között eltelt időt értjük (milliszekundumban mérve). Ha az adat *keyup* eseménnyel kezdődik, azt az eseményt hagyd figyelmen kívül.
    + A másik idősor tartalmazza a lenyomások között eltelt időt, azaz két egymást követő *keydown* esemény között eltelt időt (milliszekundumban mérve).
       
**b)** (1 pont)

Az előző feladatrészben minden gépeléshez hozzárendeltél két idősort. 

- Most tekintsd *user1* és *user2* gépeléseit, és számold ki a DTW távolságot idősorfajtánként *user1* és *user2* saját gépelései között, majd egymás gépelései között is!
<p>><font size=2>Tipp: rendezd a kiszámolt távolságokat táblázatokba a jobb áttekinthetőség kedvéért!</font></p>

- Mit tapasztalsz? Alkalmas lehet a DTW távolság arra, hogy megkülönböztessük egymástól a felhasználókat gépelési szokásaik alapján?
<p>><font size=2>Tipp: használd a *dtw* csomag *dtw* fügvényét!</font></p>

**Néhány információ az adatról:**

- Minden gépelés így kezdődik a nyers adatban: "TYPING PATTERN"

- A második sor tartalmazza a gépelő felhasználónevét

- A következő két sor egyéb (számunkra most nem fontos) információt tartalmaz (mikor gépelte le a szöveget, mennyire volt fáradt önbevallás alapján)

- Az ötödik sortól kezdődően a gépelési események szerpelnek. Minden sorban az alábbiak:
    * a gépelési esemény típusa *(keydown/keyup/keypress)*
    * event.keycode (a *keyCode* mező a hozzátartozó JavaScript eseménynél)
    * event.which
    * evenet.charCode
    * event.shiftKey
    * a JavaScript Date.getTime() függvény visszatérési értéke, azaz 1970. január 1. óta eltelt milliszekundumok száma
    
 
**A feladat megoldása szempontjából az esemény típusa, a keycode mező és az idő (milliszekundumok száma) az érdekesek számunkra!**

---